// AUTO-GENERATED by scripts/generate-config.js — do not edit by hand.
// Edit .env (locally) or your Render environment variables instead, then
// re-run: node scripts/generate-config.js
export const SUPABASE_URL = "YOUR_SUPABASE_PROJECT_URL";
export const SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY";
export const GROQ_API_KEY = "YOUR_GROQ_API_KEY";
export const GROQ_MODEL = "llama-3.3-70b-versatile";
export const ATTENDANCE_RADIUS_METERS = 200;
