// Generates js/config.js from environment variables, so real keys never have
// to be typed into a tracked file by hand.
//
// Locally: reads a .env file (if present) into process.env, then writes config.js.
// On Render: .env won't exist, but Render injects the variables you set in its
// dashboard directly into process.env, so this works the same way with no changes.
//
// Usage: node scripts/generate-config.js

const fs = require("fs");
const path = require("path");

// --- tiny .env loader (no dependencies) ---
function loadDotEnv(file) {
  if (!fs.existsSync(file)) return;
  const lines = fs.readFileSync(file, "utf8").split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    // strip matching surrounding quotes if present
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    // don't override a value Render (or your shell) already injected
    if (process.env[key] === undefined) process.env[key] = value;
  }
}

loadDotEnv(path.join(__dirname, "..", ".env"));

const {
  SUPABASE_URL = "YOUR_SUPABASE_PROJECT_URL",
  SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY",
  GROQ_API_KEY = "YOUR_GROQ_API_KEY",
  GROQ_MODEL = "llama-3.3-70b-versatile",
  ATTENDANCE_RADIUS_METERS = "200"
} = process.env;

const missing = [];
if (SUPABASE_URL.startsWith("YOUR_")) missing.push("SUPABASE_URL");
if (SUPABASE_ANON_KEY.startsWith("YOUR_")) missing.push("SUPABASE_ANON_KEY");
if (missing.length) {
  console.warn(`⚠️  Missing: ${missing.join(", ")}. Writing config.js with placeholders — the app will fall back to the welcome screen until these are set.`);
}

const output = `// AUTO-GENERATED by scripts/generate-config.js — do not edit by hand.
// Edit .env (locally) or your Render environment variables instead, then
// re-run: node scripts/generate-config.js
export const SUPABASE_URL = ${JSON.stringify(SUPABASE_URL)};
export const SUPABASE_ANON_KEY = ${JSON.stringify(SUPABASE_ANON_KEY)};
export const GROQ_API_KEY = ${JSON.stringify(GROQ_API_KEY)};
export const GROQ_MODEL = ${JSON.stringify(GROQ_MODEL)};
export const ATTENDANCE_RADIUS_METERS = ${Number(ATTENDANCE_RADIUS_METERS)};
`;

const outPath = path.join(__dirname, "..", "js", "config.js");
fs.writeFileSync(outPath, output);
console.log(`✅ Wrote ${outPath}`);
